export function getPDFTemplate(content) {
  return `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>DevGPT – AI Powered Review</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet" />
    <style>
      * {
        box-sizing: border-box;
      }

      body {
        font-family: 'Inter', sans-serif;
        background-color: #f9fafb;
        color: #1f2937;
        padding: 0;
        margin: 0;
      }

      .container {
        max-width: 850px;
        margin: 50px auto;
        background-color: #ffffff;
        border-radius: 16px;
        padding: 60px;
        box-shadow: 0 15px 30px rgba(0, 0, 0, 0.05);
        border: 1px solid #e5e7eb;
      }

      header {
        text-align: center;
        margin-bottom: 50px;
        border-bottom: 2px dashed #e0e7ff;
        padding-bottom: 20px;
      }

      header h1 {
        font-size: 32px;
        font-weight: 700;
        margin: 0;
        background: linear-gradient(to right, #3b82f6, #8b5cf6);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
      }

      .section {
        margin-bottom: 48px;
      }

      .section-title {
        font-size: 18px;
        font-weight: 600;
        margin-bottom: 14px;
        color: #3b82f6;
        display: flex;
        align-items: center;
        gap: 10px;
      }

      .section-content {
        font-size: 15.5px;
        line-height: 1.8;
        color: #374151;
        background-color: #f9fafb;
        padding: 20px;
        border-radius: 10px;
        border: 1px solid #e5e7eb;
        white-space: pre-wrap;
      }

      .badge {
        font-size: 12px;
        font-weight: 600;
        padding: 4px 10px;
        border-radius: 999px;
        display: inline-block;
        text-transform: uppercase;
      }

      .risk-high {
        background-color: #fee2e2;
        color: #b91c1c;
      }

      .risk-medium {
        background-color: #fef9c3;
        color: #92400e;
      }

      .risk-low {
        background-color: #dcfce7;
        color: #166534;
      }

      a {
        color: #2563eb;
        word-break: break-word;
        text-decoration: underline;
      }

      footer {
        text-align: center;
        font-size: 13px;
        color: #9ca3af;
        margin-top: 60px;
        padding-top: 20px;
        border-top: 1px dashed #e5e7eb;
      }

      .icon {
        width: 18px;
        height: 18px;
        vertical-align: middle;
      }

      /* Hide buttons or interactive elements */
      .hide-in-pdf {
        display: none !important;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <header>
        <h1>DevGPT – AI Powered Review</h1>
      </header>

      ${content}

      <footer>
        Generated by DevGPT • Your AI Code Review Assistant
      </footer>
    </div>
  </body>
  </html>
  `;
}
